### ISSUE TITLE
ffmpeg warning "stream 0, timescale not set" appears after adding cover art to. mp4/.m4a

### ISSUE THREAD

**Issue by ponsfoot** [Martchus/tageditor#1]
Hi,

After adding cover art to .mp4/.m4a file, the following warning appears (when opening).

> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55a51db589a0] stream 0, timescale not set

If not adding cover, this doesn't appear.
There seems to be no problem to play by this message, though :)

Version: 2.0.0
OS: ArchLinux (x86_64)
Packages from your binary repository

result of ffmpeg -i of the file before adding cover:

> ffmpeg -i 01\ -\ Signs\ Of\ Spring.m4a.bak 
> ffmpeg version 3.1.4 Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 6.2.1 (GCC) 20160830
>   configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
>   libavutil      55. 28.100 / 55. 28.100
>   libavcodec     57. 48.101 / 57. 48.101
>   libavformat    57. 41.100 / 57. 41.100
>   libavdevice    57.  0.101 / 57.  0.101
>   libavfilter     6. 47.100 /  6. 47.100
>   libavresample   3.  0.  0 /  3.  0.  0
>   libswscale      4.  1.100 /  4.  1.100
>   libswresample   2.  1.100 /  2.  1.100
>   libpostproc    54.  0.100 / 54.  0.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '01 - Signs Of Spring.m4a.bak':
>   Metadata:
>     major_brand     : mp42
>     minor_version   : 0
>     compatible_brands: M4A mp42isom
>     creation_time   : 2013-04-25 02:25:25
>     iTunSMPB        :  00000000 00000A40 000003D8 0000000000B2D9E8 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
>     track           : 1
>     artist          : UNCHAIN
>     album           : rapture
>     date            : 2008
>     genre           : JPop
>     title           : Signs Of Spring
>     encoder         : Nero AAC codec / 1.5.4.0
>   Duration: 00:04:25.87, start: 0.059501, bitrate: 232 kb/s
>     Chapter #0:0: start 0.059501, end 265.927979
>     Metadata:
>       title           : 
>     Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 230 kb/s (default)
>     Metadata:
>       creation_time   : 2013-04-25 02:25:25
>       handler_name    : Sound Media Handler
> At least one output file must be specified
> 

And after adding cover:

> ffmpeg -i 01\ -\ Signs\ Of\ Spring.m4a
> ffmpeg version 3.1.4 Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 6.2.1 (GCC) 20160830
>   configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
>   libavutil      55. 28.100 / 55. 28.100
>   libavcodec     57. 48.101 / 57. 48.101
>   libavformat    57. 41.100 / 57. 41.100
>   libavdevice    57.  0.101 / 57.  0.101
>   libavfilter     6. 47.100 /  6. 47.100
>   libavresample   3.  0.  0 /  3.  0.  0
>   libswscale      4.  1.100 /  4.  1.100
>   libswresample   2.  1.100 /  2.  1.100
>   libpostproc    54.  0.100 / 54.  0.100
> **[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564acd8939a0] stream 0, timescale not set**
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '01 - Signs Of Spring.m4a':
>   Metadata:
>     major_brand     : mp42
>     minor_version   : 0
>     compatible_brands: M4A mp42isom
>     creation_time   : 2013-04-25 02:25:25
>     iTunSMPB        :  00000000 00000A40 000003D8 0000000000B2D9E8 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
>     track           : 1
>     artist          : UNCHAIN
>     album           : rapture
>     date            : 2008
>     genre           : JPop
>     title           : Signs Of Spring
>     encoder         : Nero AAC codec / 1.5.4.0
>   Duration: 00:04:25.87, start: 0.059500, bitrate: 234 kb/s
>     Chapter #0:0: start 0.059501, end 265.927978
>     Metadata:
>       title           : 
>     Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 230 kb/s (default)
>     Metadata:
>       creation_time   : 2013-04-25 02:25:25
>       handler_name    : Sound Media Handler
>     Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
> At least one output file must be specified

Thank you for useful software and providing binary repo.

Best regards

**Comment by Martchus** [comment]
Hi,
I can reproduce the issue. However, I suspect that there's nothing wrong with the Tag Editor (or the tagparser library).

If you look at the output where the warning occurs you'll notice that there's also an additional video stream detected. However, this stream is just the cover. I added a PNG cover and ffmpeg displays the following additional stream:
```
Stream #0:1: Video: png, rgb24(pc), 1940x1048 [SAR 3779:3779 DAR 485:262], 90k tbr, 90k tbn, 90k tbc
```
I guess treating the cover as a stream is intended. It allows you to extract the cover again:
```
ffmpeg -i test2.m4a -map 0:1 cover.png
```
Of course ffmpeg will not find any timescale information for the cover in the file and hence prints accidentally the warning.

I also doubt that the timescale info for the actual audio track is missing because
* then the duration could not be calculated anymore but this is still the case.
* if you remove the cover again, the warning disappears again.
* the warning occurs when opening any MP4 file with cover (also files never touched by the Tag Editor).

So looks more like a misleading ffmpeg warning to me.

Best Regards

**Comment by Martchus** [comment]
Seems that this is a known issue:
* https://lists.ffmpeg.org/pipermail/ffmpeg-user/2013-April/014470.html
* http://stackoverflow.com/questions/17798709/ffmpeg-how-to-embed-cover-art-image-to-m4a

**Comment by ponsfoot** [comment]
Okay, I understand.
Thank you for the info and I'll try ffmpeg-libfdk_aac.
