### ISSUE TITLE
Rewriting problem on large mp4 files?

### ISSUE THREAD

**Issue by gigend** [Martchus/tageditor#100]
Hello, I want to add cover art to my mp4 file which is more than 3GB in size. However, the process is very long. I've been looking for a way through the settings in the GUI in issue section, namely padding settings, but it's the problem is still the same, I have to rewrite again and bring up the bak file.

Is it normal to edit mp4 tags like that? have to rewrite and require a long process and there are no proper settings (especially for the GUI because I don't understand the CLI)?

Thanks for the answer.

**Comment by Martchus** [comment]
> However, the process is very long.

A rewrite shouldn't take *that* long. It eventually finishes though, right? How long does it take exactly?

> Is it normal to edit mp4 tags like that?

I chose these defaults to be conservative. It is always good to have a backup and it is generally nice to avoid wasting disk space for padding. For smaller files this makes sense and the tag editor is supposedly mainly used for audio files.

> have to rewrite and require a long process and there are no proper settings

There are settings to configure this. In fact, this tag editor provides more details settings than most other tools. To avoid rewriting, set the minimum padding to 0 and the maximum padding to a very high value. This way the tag editor won't rewrite the file even if there's no padding at all or if it would result in a file with a lot of padding. Be also sure not to have "Force rewrite …" checked. Be also sure not to have any of the "Use preferred position …" boxes checked.

> and bring up the bak file

What do you mean with "bring up" here? Note that you can configure the directory to store backup files (so you can easily delete them in the end from one place). Be sure to use a directory in the same filesystem to avoid an unnecessary copy.

**Comment by gigend** [comment]
Thank you for the answer, sorry if the language is a bit confusing.

> A rewrite shouldn't take that long. It eventually finishes though, right? How long does it take exactly?

For one **5.17 GB mp4 file with audio and video**, I only want to add about 100 KB of cover art, it takes about ± 2 minutes.

> I chose these defaults to be conservative. It is always good to have a backup and it is generally nice to avoid wasting disk space for padding. For smaller files this makes sense and the tag editor is supposedly mainly used for (small) audio files.

Yes, for small audio files it's not a problem, but if the files are large (for example an mp4 larger than 5 GB, with audio and video) does it must to be rewritten? or can it be by setting the padding section?

> There are settings to configure this. In fact, this tag editor provides more details settings than most other tools. To avoid rewriting, set the minimum padding to 0 and the maximum padding to a very high value. This way the tag editor won't rewrite the file even if there's no padding at all or if it would result in a file with a lot of padding. Be also sure not to have "Force rewrite …" checked. Be also sure not to have any of the "Use preferred position …" boxes checked.

![image](https://user-images.githubusercontent.com/54487902/217795703-8e67bc9c-a27d-4d66-89c7-16cafb50e8b3.png)
Are these settings correct for my case above?

> What do you mean with "bring up" here? Note that you can configure the directory to store backup files (so you can easily delete them in the end from one place). Be sure to use a directory in the same filesystem to avoid an unnecessary copy.

it means that it always generates a .bak file during the saving process (when I try to cancel the saving process, I rename and delete the .bak extension to restore the original file, is that correct?).

**Comment by Martchus** [comment]
> does it must to be rewritten? or can it be by setting the padding section?

It must not be rewritten. I've already stated how a rewrite can be avoided.

> Are these settings correct for my case above?

No, they're not. As stated before, be sure that "Use preferred …" options are *not* checked. Additionally, you might be adding a few more zeros to the maximum padding setting. (The padding might become as big as the index because when  putting tags at the end also the index must be put at the end. This is a limitation of MP4.)

> when I try to cancel the saving process, I rename/delete the .bak extension to restore the original file, is that correct?

Yes. However, when you cancel the saving gracefully, the file should actually be renamed back automatically.

---

Maybe it makes sense to add some buttons to set these settings according to presets (e.g. "Avoid rewrite" vs. "Faststart").

**Comment by gigend** [comment]
![image](https://user-images.githubusercontent.com/54487902/217806234-648eb93e-5f13-43c1-ad58-c481974269b1.png)

ok thank you, I use settings like this, and I try to save them, and it's true that the process of saving is very instant!

but, the setting like this is correct right? won't damage the original mp4 file?

thanks for the solution, the GUI is very useful for amateur user like me for who hard to understand the documentation.

**Comment by Martchus** [comment]
> but, the setting like this is correct right? won't damage the original mp4 file?

If you can put settings here that lead to a damaged file than that would be a bug. I'm not aware of any bugs at this point (but thinking of bugs there were in the past, really make sure you use the latest version!).

The downside to this is that the index is kept at the end. So a player needs to seek to the very end of the file first to be able to play it. Maybe your file was like this before anyways, though. Another downside is that if the tag editor, the OS or your entire system crashes for some reason (e.g. power cut) then you end up with a half-amended and thus possibly broken file with no backup.
