### ISSUE TITLE
inquiry: thumbnails for mpeg files

### ISSUE THREAD

**Issue by boldcompany** [Martchus/tageditor#101]
Windows automatically generates thumbnails for mpeg (.mpg) files.

It seems the mpeg specification does not support tagging. Obviously, a user can run a utility to apply non-standard tags to a .mpg file, but software may not recognize tags applied in this way.

Preferring a clean, standard approach, what is the best way to change the thumbnails, setting custom thumbnails for .mpg files such that Windows displays the new thumbnails in File Explorer icon views?

**Comment by Martchus** [comment]
The formal name of the format you mean with "mpeg files" is "[MPEG Program Stream](https://en.wikipedia.org/wiki/MPEG_program_stream)". This format is not supported by this tag editor and as far as I know does not even support storing this kind of tag information (as you already stated).

I don't know what formats the Windows Explorer can read the cover/thumbnail from except MP4. Possibly it also supports Matroska. So you could remux your video/audio content to MP4 and then just add a cover tag. You could also give Matroska a shot (where the cover is usually added as an attachment (see https://matroska.org/technical/attachments.html). Both formats can be muxed with ffmpeg (when using `-c copy` ffmpeg will not re-convert the video/audio streams). You could also use the format-specific tools mp4box and mkvtoolnix.

**Comment by boldcompany** [comment]
Thank you very much for this helpful, thorough answer!
