### ISSUE TITLE
Why does tageditor crop thumbnail image?

### ISSUE THREAD

**Issue by JohnnyZ716** [Martchus/tageditor#102]
So I've noticed that when I insert an image for a video thumbnail in windows 10, the photo in the video thumbnail when viewed is cropped significantly. Most notably the sides of the photo. Is there a certain size or dimensions a photo must be in order for the photo not to be cropped?

**Comment by Martchus** [comment]
The tag editor does not crop anything. Even if you wanted, that's nothing I have ever implemented. Most likely it is the Windows explorer that does the cropping on the fly when showing those thumbnails.

The tag editor also allows displaying/extracting a cover image. So you can re-extract a cover you've added to verify that it is indeed not cropped. You can of course also use another tool like ffmpeg to extract the cover and verify that it is not cropped.
