### ISSUE TITLE
v3.8.1 for Windows being flagged as malicious

### ISSUE THREAD

**Issue by Taomyn** [Martchus/tageditor#106]
https://www.virustotal.com/gui/file/e17c4c2f63560d528be7164d5ae8e9582a9b8b09904223b7e699008c1942659f

![image](https://github.com/Martchus/tageditor/assets/4365929/b89307e9-a95d-43c7-a4c4-cd04e5ea1eaf)

**Comment by Martchus** [comment]
This is most likely just a false alert, same as for my other project Syncthing Tray. So I'm closing this with a reference to https://github.com/Martchus/syncthingtray/issues/189.
