### ISSUE TITLE
How to edit a field on multiple files at once

### ISSUE THREAD

**Issue by GamingLegion** [Martchus/tageditor#107]
I'm trying to set multiple files with an album name, artist, and cover. Is there a way to do that? I've been saving then opening the next file over and over.

**Comment by Martchus** [comment]
Have a look at https://github.com/Martchus/tageditor#modifying-tags-and-track-attributes.

**Comment by Martchus** [comment]
If this is about the GUI: It has no batch processing. You can however change the setting "Clear previous values" to "Keep previous values, …" so it at least keeps album name, artist, cover and other tags when opening the next file. That makes it still quite convenient to use apart from the slight waiting time when going from one file to the next.

**Comment by Martchus** [comment]
I guess this can be closed right away considering there was no response.
