### ISSUE TITLE
Defender sees 3.8.1 CLI as a virus.

### ISSUE THREAD

**Issue by L0garithmic** [Martchus/tageditor#110]
JFYI windows defender sees 3.8.1 cli exe as a virus. Not a big deal, just figured you might want to see why.

**Comment by Martchus** [comment]
I'm not going to do anything about it. It is up to Microsoft to fix their broken AV software and this is clearly out of the scope of this project. That it is producing a false positive for this tiny bit of software show how useless AV software is.
