### ISSUE TITLE
VirusTotal flags tageditor-3.9.0-x86_64-w64-mingw32-cli.exe

### ISSUE THREAD

**Issue by bcurran3** [Martchus/tageditor#112]
I'm sure it's false, but pointing it out.

RE: tageditor-3.9.0-x86_64-w64-mingw32-cli.exe

38 security vendors and no sandboxes flagged this file as malicious

https://www.virustotal.com/gui/file/3c00b92e8db78bb926306db4162f1408b814f4b382717b24b4e92016c87fec39

**Comment by Martchus** [comment]
At this point there's no need to point it out for every single version anymore.

**Comment by Martchus** [comment]
At this point there's no need to point it out for every single version anymore. There's nothing to be said that hasn't already been said in other tickets.

**Comment by tommaier123** [comment]
I think it would be good to add that to the readme or leave one issue open.
Another option would be to provide the CLI version in a separate file, most people will probably use the GUI.

**Comment by Martchus** [comment]
> I think it would be good to add that to the readme

Good idea. Then I can at least just link to that readme section when people create issues.

> most people will probably use the GUI.

People have filed issues regarding the CLI on Windows (and the CLI wrapper binary solves these) so I don't think that's true. One reason to use Tag Editor and not one of the more popular alternatives is probably the CLI which is very useful for scripting.
