### ISSUE TITLE
[Change Request] Defender sees CLI as a virus

### ISSUE THREAD

**Issue by David-Maisonave** [Martchus/tageditor#114]
This is related to issue https://github.com/Martchus/tageditor/issues/110. 
I don't use the CLI, and I believe that would be true for most users.

Can the ZIP package be changed so that the CLI is in it's own zip file separated from the GUI app?

That will allow the average user to download the GUI app without having to go through multiple steps to get through the AV (Defender).

Thanks

**Comment by Martchus** [comment]
I created the CLI wrapper to fix problems people have complained about and I use the CLI sometimes myself. The CLI is actually also one of the features that sets this application apart from other more popular ones.

So there's no simple and good solution to that within the scope of this projects. (A good solution would be that the AV vendor would fix their broken software but that's out of scope here.)

**Comment by David-Maisonave** [comment]
Why not have a package that excludes the CLI? User who want the CLI can pick the package which has the CLI?
Fixing the AV is outside of the scope of this project, but not package management.

**Comment by sertraline** [comment]
I'm here because Firefox now also detects file as malicious (https://virustotal.com/gui/file/b765ff8fdedf8dc1d586c9a017ad9125286e59db3d0bc5b38c032e9e71956d8a). Just to note, abandoning antivirus is not an option for Windows users who use Home edition, since they don't have a group policy editor available to turn Defender off.

![image](https://github.com/Martchus/tageditor/assets/36751007/2a72a100-2f66-40a6-b162-5c333b3fc5e6)

**Comment by Martchus** [comment]
You'll just have to allow it in defender. But yes, this gets more and more annoying. I'll try what's suggested in https://github.com/Martchus/syncthingtray/issues/207#issuecomment-1832601777.

**Comment by Martchus** [comment]
Note that I filed a submission/dispute for my other project Syncthing Tray, see https://github.com/Martchus/syncthingtray/issues/207#issuecomment-1834457752. I also mentioned Tag Editor. Let's see whether that will help.

**Comment by Martchus** [comment]
The submission/dispute worked for Syncthing Tray which remains undetected according to Virus Total. The CLI of Tag Editor on the other hand is still wrongly detected so I suppose I'll have to file a separate submission.
