### ISSUE TITLE
Trojan:Win64/Rozena.CEW!MTB found in tageditor-3.9.0-x86_64-w64-mingw32.exe.zip

### ISSUE THREAD

**Issue by Escape888** [Martchus/tageditor#115]
Trojan:Win64/Rozena.CEW!MTB

This program is dangerous and executes commands from an attacker.

Downloads\tageditor-3.9.0-x86_64-w64-mingw32.exe.zip

[https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin64%2FRozena.CEW!MTB&threatid=2147893397](url)

**Comment by Martchus** [comment]
This is a known problem, see #114. So I'm closing this as duplicate.

**Comment by Escape888** [comment]
What is CLI and what does it do?

**Comment by Martchus** [comment]
It allows you to use the command-line interface mentioned in the README within a terminal/console under Windows. This feature has been requested by Windows users in the past.
