### ISSUE TITLE
[Question] CLI tag adding (track/disk total, engineer, producer) to audio files

### ISSUE THREAD

**Issue by incogthedev** [Martchus/tageditor#118]
Hello,

I was looking to see if there was an option to add track/disc total via CLI at all?

Also, do the engineers/preformer/producer tags not work in audio files?

**Comment by Martchus** [comment]
What's supported depends on the container format and not on whether an audio track is present or not.

Note that most container formats use a combined field for the track/disc position so the total is specified as mentioned in the README example. For Matroska - which is a notable exception - you'll need to specify the totals as separate fields. 

Maybe I should add a way to probe what fields are supported in the CLI. For now you can simply use the GUI for that. If a field doesn't show up in the GUI editor despite being configured in the settings dialog it is not supported by the file format.

**Comment by Martchus** [comment]
Since this is probably about Matroska which is unfortunately quite unconventional and thus confusing. So I added a section about Matroska to the README file: https://github.com/Martchus/tageditor?tab=readme-ov-file#matroska-related-remarks

**Comment by incogthedev** [comment]
It's actually about audio files like FLAC/MP3/OGG!

**Comment by Martchus** [comment]
Ok, then your question should be answered by the examples that were already in the README, just specify e.g. `track=5/15 disk=1/2`.

**Comment by incogthedev** [comment]
> Ok, then your question is answered by the examples that were already in the README, just specify e.g. `track=5/15 disk=1/2`.

Aren't they usually seperate fields, though?

**Comment by Martchus** [comment]
In ID3v2 and MP4 tags there is one field for the track position that includes both - the track number and total. The same counts for the disk.

In Matroska those are separate fields.

In the underspecified Vorbis comments it annoyingly depends on the convention. This Tag Editor uses one field but is able to read tags using separate fields. The underlying library would actually be able to control that but I think I have never exposed this functionality in the CLI or GUI.

**Comment by Martchus** [comment]
Oh, looks like I actually did expose this setting. So you can use `--preserve-total-fields` with the `set` operation of the CLI and there's also a GUI setting. To actually set the totals as individual fields you proably have to resort to using native field IDs, see the "Sets custom fields" example in the README.
