### ISSUE TITLE
"'tageditor --help' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by cavalrymargarine0x1** [Martchus/tageditor#121]
Hi, i'm on Windows 10 and trying to use tageditor CLI. When I open a cmd prompt in the tageditor folder where `tageditor-3.9.3-x86_64-w64-mingw32-cli.exe` is, cmd returns `"'tageditor' is not recognized as an internal or external command, operable program or batch file."` when I type `tageditor --help`

I tried renaming the cli exe to just simply `tageditor-cli.exe` after reading the [Windows-specific issues section](https://github.com/Martchus/tageditor#windows-specific-issues) and adding the folder containing it to PATH but doing that didn't fix the problem

Any help with this would be appreciated. thanks!

**Comment by Martchus** [comment]
The file names of the executables contain the version and build target to better distinguish different builds.

As you've already figured out it is possible to rename the executables as long as you rename them in accordance with each other. Alternatively one can simply call the executables using their full original name which is probably how I would have expected people to use it (under Windows, I personally use the CLI only under Linux).
