### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#14]
I am getting this error when trying to build static TagEditor:

~~~
[100%] Linking CXX executable tageditor.exe
/usr/lib/gcc/x86_64-w64-mingw32/5.4.0/../../../../x86_64-w64-mingw32/bin/ld:
  cannot find -lc++utilities_static
/usr/lib/gcc/x86_64-w64-mingw32/5.4.0/../../../../x86_64-w64-mingw32/bin/ld:
  cannot find -ltagparser_static
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/tageditor.dir/build.make:165: tageditor.exe] Error 1
make[3]: Leaving directory '/tmp/tageditor'
make[2]: *** [CMakeFiles/Makefile2:132: CMakeFiles/tageditor.dir/all] Error 2
make[2]: Leaving directory '/tmp/tageditor'
make[1]: *** [Makefile:117: all] Error 2
make[1]: Leaving directory '/tmp/tageditor'
make: *** [makefile:5: tageditor] Error 2
~~~

I think the problem is that for some reason TagEditor is looking for
libtagparser_static.a when what I have is libtagparser.a. Here are my build
scripts if that helps

- http://github.com/svnpenn/glade/blob/master/tageditor/install.sh
- http://github.com/svnpenn/glade/blob/master/tagparser/install.sh
- http://github.com/svnpenn/glade/blob/master/cpp-utilities/install.sh

**Comment by Martchus** [comment]
I guess I now what the problem is. I'll fix this later.

**Comment by Martchus** [comment]
Commit https://github.com/Martchus/cpp-utilities/commit/4503f3fd9d2657fe5468bf5788953e8a1466c3ad might fix it.

**Comment by svnpenn** [comment]
i will try to test it after work, thanks

**Comment by svnpenn** [comment]
That commit does allow TagEditor to find TagParser. However after that it was
not linking statically against libgcc and libstdc++. I fixed that like this:

~~~
-DCMAKE_EXE_LINKER_FLAGS='-static-libgcc -static-libstdc++'
~~~

However after that it will only link shared/dynamic to libwinpthread:

~~~
tageditor.exe: error while loading shared libraries: libwinpthread-1.dll: cannot
open shared object file: No such file or directory
~~~

**Comment by svnpenn** [comment]
That commit does allow TagEditor to find TagParser. However after that it was
not linking statically against libgcc and libstdc++. I fixed that like this:

~~~sh
-DCMAKE_EXE_LINKER_FLAGS='-static-libgcc -static-libstdc++'
~~~

However after that it will only link shared/dynamic to libwinpthread:

~~~
tageditor.exe: error while loading shared libraries: libwinpthread-1.dll: cannot
open shared object file: No such file or directory
~~~

It looks like this file was causing the problem, removing it fixed it:

~~~
rm /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.dll.a
~~~

http://wiki.videolan.org/Win32Compile#Static_compilation_of_plugins

I would prefer a Cmake option to removing a file, but this might have to do.

**Comment by Martchus** [comment]
So far, you enabled *building* static libraries. To enable *linking against* static libraries, you need to enable `STATIC_LINKAGE`. Otherwise the build system will prefer linking against dynamic libraries.

You should not have to set `CMAKE_EXE_LINKER_FLAGS`, this should be done by the build script when `STATIC_LINKAGE` linkage is enabled.

> removing it fixed it

If remove the dynamic (import) libraries, the build script falls back to link against static ones.

> I would prefer a Cmake option to removing a file

This makes no sense because the user executing the build script usually does not have the rights to delete an installed library.

Also, ensue that all dependencies are available as static libraries.

**Comment by svnpenn** [comment]
Thanks again. Adding:

~~~
-DSTATIC_LINKAGE=1
~~~

allowed me to remove:

~~~
rm -f /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.dll.a
-DCMAKE_EXE_LINKER_FLAGS='-static-libgcc -static-libstdc++'
~~~

and still have a correct build.

**Comment by Martchus** [comment]
Nice, and also thanks for providing all the feedback.
