### ISSUE TITLE
Many Matroska tags are unsupported

### ISSUE THREAD

**Issue by danlamanna** [Martchus/tageditor#17]
When trying to edit some of the lesser used Matroska tags into my videos, I encounter the error message programmed [here](https://github.com/Martchus/tageditor/blob/1a181d36d4c7e6fd9878b83992ec70ffee756d90/cli/mainfeatures.cpp#L535).

From the looks of it, the majority of tags listed under the [official tag specification](https://www.matroska.org/technical/specs/tagging/index.html#tags) don't work with tageditor.

The Matroska specification also allows (though warns against) custom key value pairs as tags.

**Comment by Martchus** [comment]
The tag editor currently does not allow to specify fields using the native identifiers of the particular file format. So only the fields where [mapping from and to general identifiers](https://github.com/Martchus/tagparser/blob/master/matroska/matroskatag.cpp#L18) is defined are supported.

I already thought it would be useful to be able to use native field identifiers. There is also no support for nested tags yet. However, implementing those features requires some thinking about how to design the CLI syntax/args for it and I haven't had the time yet. Problem is that the CLI syntax is already a bit complicated/unintuitive (at least when specifying affected tags and targets).

Till this is implemented you could extend the mapping (should be trivial to implement) or use the tagparser library directly.

**Comment by Martchus** [comment]
Specifying native IDs has been implemented, see https://github.com/Martchus/tagparser/commit/b4e167bd7159823efcfa4a3d3285e783d2f2a2fa and https://github.com/Martchus/tageditor/commit/d99956f4c9e5571b7060bef2591f7e38f323c2bb

There's an example how to use it in the README.

**Comment by Martchus** [comment]
Now all official Martoska tags are supported.
