### ISSUE TITLE
Window does not fit to laptop screen (1366x768)

### ISSUE THREAD

**Issue by glaubersm** [Martchus/tageditor#20]
My screenshot says by itself.

![tageditor](https://user-images.githubusercontent.com/15967631/29297956-da91c236-813a-11e7-86d8-4618e6c06fc9.png)

**Comment by Martchus** [comment]
You could try to hide the MusicBrainz search or move it to the right. But yes, the search should not take so much space. At least its tree view should be smaller and maybe show a scroll bar if needed.

**Comment by Martchus** [comment]
The issue that the search is unable to shrink should be reduced now.

Note that even before the change the Tag Editor fits quite well on a 1366x768 screen. You just have to move the search to the right or hide it completely if you don't need it:
![tag editor 1366x768](https://user-images.githubusercontent.com/10248953/29338096-1eba8680-8214-11e7-8603-3612f73c8515.png)

**Comment by Martchus** [comment]
Should be fixed. Just reopen if something is missing.
