### ISSUE TITLE
Errant wrapping if output is redirected

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#25]
If you do something like this:

~~~
tageditor --help > help.txt
~~~

or this:

~~~
tageditor --help | head
~~~

you end up with weird wrapping:

~~~
Tag Editor, version 2.2.5-337.b1b071a
Linked against: C++ Utilities: 4.11.0-398.4011040, Tag Parser: 6.5.0-336.f65b908

Available arguments:
--qt-widgets-gui
  shows a Qt widgets based graphic
  al user interface (the applicati
  on has not been built with Qt wi
  dgets support)
  --file, -f [path]
~~~

**Comment by svnpenn** [comment]
Looks like problem is with recent cpp-utilities:

- v4.10.0 BAD
- v4.9.2 GOOD

**Comment by Martchus** [comment]
I do manual wrapping for some parts of the help output so indentation is not messed when the line would be wrapped automatically.

Apparently this doesn't seem to work under Windows when using pipe. Seems like `GetConsoleScreenBufferInfo()` returns inappropriate values in that case. Note that really only the help should be affected.

This would be the relevant code for improving or disabling the feature in a configurable way: https://github.com/Martchus/cpp-utilities/blob/master/application/commandlineutils.cpp#L52

**Comment by svnpenn** [comment]
@Martchus you set `rows` as `X` and `columns` as `Y`, you have those reversed:

http://github.com/Martchus/cpp-utilities/blob/9829dbe/application/commandlineutils.cpp#L55-L60

**Comment by svnpenn** [comment]
https://github.com/Martchus/cpp-utilities/pull/8

**Comment by Martchus** [comment]
So this is fixed by merging https://github.com/Martchus/cpp-utilities/pull/8?

**Comment by svnpenn** [comment]
yes thanks
