### ISSUE TITLE
c++utilities 4.11.0

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#26]
TagEditor now requires c++utilities 4.11.0:

http://github.com/Martchus/tageditor/blob/b1b071a/CMakeLists.txt#L207

However that version has not been tagged:

http://github.com/Martchus/cpp-utilities/tags

Looks like this one:

http://github.com/Martchus/cpp-utilities/commit/4011040

**Comment by Martchus** [comment]
Correct. The current development version of tageditor depends on the current development version of c++utilities. That's fine.

**Comment by cup** [comment]
https://github.com/Martchus/tagparser/issues/12
