### ISSUE TITLE
Machine parsable duration

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#27]
Using this file (regionsAllowed=DE,US):

~~~
youtube-dl --format 140 --output journey.m4a k5dX9sjXYVk
~~~

FFmpeg can get machine parsable duration:

~~~
$ ffprobe -v 0 -of csv=p=0 -show_entries stream=duration journey.m4a
610.800998
~~~

However TagEditor cannot:

~~~
$ tageditor -if journey.m4a
Technical information for "journey.m4a":
  Container format: MPEG-4 Part 14
    Document type                 isom
    Version                       512
    Duration                      10 min 10 s 801 ms
~~~

**Comment by Martchus** [comment]
It is printing the duration in the way I like it most. Of course alternative formats could be implemented (like total seconds).

BTW: Maybe using the tagparser library directly is a better approach for what you're trying to achieve. Its API is very simple to use.

**Comment by Martchus** [comment]
Implemented by introducing `--time-span-format` option:

```
--time-span-format [measures/colons/seconds]
  specifies the output format for time spans
```
eg. 
* measures: 3 min 26 s 17 ms 210 µs 800 ns
* colons: 00:03:26.0172108
* seconds: 206.0172108

**Comment by svnpenn** [comment]
Confirmed - thanks

~~~
$ tageditor info --files journey.m4a --time-span-format seconds | grep Duration
    Duration                      610.801
    Duration                      610.800907
~~~
