### ISSUE TITLE
few question about images changing

### ISSUE THREAD

**Issue by DemonRem** [Martchus/tageditor#34]
Does this Application Support windows platform ?
can i change song image to a custom image ?
for example windows 10 have is own media player and the microsoft windows media player
they support in the software changes?

**Comment by Martchus** [comment]
1. Yes, there are binaries for i686 and x86_64 in the release section on GitHub.
2. Yes, changing the cover is possible for all formats supporting it.
3. I don't understand the question. But since it is about Windows Media Player I likely don't know anyways.

**Comment by DemonRem** [comment]
thank you
