### ISSUE TITLE
Can't Figure Out How to Use on Kubuntu 18.04?

### ISSUE THREAD

**Issue by SarahSzabo** [Martchus/tageditor#37]
I can't figure out how to use this on Kubuntu 18.04.

I'm really interested in using this library to add thumbnails to .opus files, but can't for the life of me figur e out how to get this program running on my machine. There is no repository for it, and using the typical ./configure -> make -> sudo make install, scheme doesn't appear to work.

Is there any way I can get the CLI version of tageditor working on my system? Can you tell me exactly how to do so if this is the case?

**Comment by Martchus** [comment]
> in using this library

This project contains an application featuring a command-line interface and a Qt GUI. For a library, have a look at [tagparser](https://github.com/Martchus/tagparser).

> to add thumbnails

This project (and the underlying library) are not able to *generate* thumbnails. It is only possible to add  existing images as cover art or (in case of Matroska files) attachment.

> ./configure -> make -> sudo make install

This is how autotools-based projects are usually built. The tag editor uses CMake. So you have to follow the way CMake projects are typically built.

Note that there's actually no need to use sudo. Just install to some directory inside your home. Or just use the binary from the build directory without installing anything.

> Is there any way I can get the CLI version of tageditor working on my system?

Very likely.

> Can you tell me exactly how to do so if this is the case?

Sorry, I'm not using Ubuntu and can't support each and every distribution. Did you try to follow these instructions: https://github.com/Martchus/tageditor#building-this-straight ? It should work under most distributions. You just need to ensure all dependencies are available (maybe install devel packages or build them yourself, too).

**Comment by Martchus** [comment]
Closing as no further questions have been asked.
