### ISSUE TITLE
AppImage still having 'track' option conflicts

### ISSUE THREAD

**Issue by analike** [Martchus/tageditor#39]
From the changes i see the issue of setting _tracknumber_ using the **track** option has been has been fixed.

But the latest AppImage i downloaded few minutes ago still face this problem.

Can i get a link to an AppImage without the issue?

Thanks.

**Comment by Martchus** [comment]
I can retrigger the build in OBS later.

**Comment by analike** [comment]
Thanks. I'll be waiting.

**Comment by Martchus** [comment]
The new build should be available: https://build.opensuse.org/package/show/home:mkittler:appimage:vcs/tageditor

**Comment by analike** [comment]
Thanks. Working great.
