### ISSUE TITLE
Tag Editor icon is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [Martchus/tageditor#48]
Hi

I use tageditor 3.2.1-1 on Arch Linux running KDE Plasma 5.16.3 desktop environment
on Wayland.
As we can see in the screenshot below, the title bar of Tag Editor shows a Wayland generic icon instead of the its own icon. The same Wayland generic icon also appears in the alt+tab menu.
Maybe the following link can help you to solve this issue
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

![tageditor](https://user-images.githubusercontent.com/15967631/61718335-2b238500-ad39-11e9-9312-263c15dfe724.png)

**Comment by Martchus** [comment]
I have already recognized that you opened this [issue for subtitlecomposer](https://github.com/maxrd2/SubtitleComposer/issues/141) as well and did the required fixes for my applications, too. So icons and context menus should already work with latest master. You could use my binary Arch Linux repo for Git packages or build them yourself from the AUR.

**Comment by Martchus** [comment]
When building Git packages yourself, be aware of https://github.com/Martchus/PKGBUILDs/issues/99#issuecomment-513471386.

**Comment by Martchus** [comment]
I guess this can be closed then. If it doesn't work after all, just reopen.
