### ISSUE TITLE
Bulk adding thumbs?

### ISSUE THREAD

**Issue by GiacomoLaw** [Martchus/tageditor#49]
![image](https://user-images.githubusercontent.com/9038673/64920265-65475b00-d7ad-11e9-8edc-84761e8e2c68.png)

Is there any way to run it on an entire library? The above shows my naming convention - thanks!

Would be great if there was a `.bat` file or something I could run to quickly apply them all.

**Comment by Martchus** [comment]
You could write a small Bash/Perl/Python/... script indeed. Sounds like a suitable problem to start learning the basics of programming :-)

Note that while this is likely doable with a .bat script this wouldn't be my first choice.

There's also the option to use the tagparser library directly if you want to use C++.

**Comment by GiacomoLaw** [comment]
Okay, thanks - I'll take a look at writing a Python script :D
