### ISSUE TITLE
Saved tags don't show up in Windows explorer.

### ISSUE THREAD

**Issue by brachna** [Martchus/tageditor#5]
Windows 8.1 x64
"tageditor-devel-2-static-x86_64-w64-mingw32.tar.xz"

mp3 file resaved using tageditor doesn't show tags in Windows explorer. Tried resaving with different ID3v1 and ID3v2 tags.

**Comment by Martchus** [comment]
I can reproduce - this is a regression. I'll try to fix it.

**Comment by Martchus** [comment]
* Tags of the saved file (containing still ID3v2 and ID3v1 tags) aren't shown in Explorer and in VLC player (under Windows).
* Tags are shown in Tag Editor, though.
* Tags of the exact same file are shown under Arch Linux in all media players I've tested (including VLC).
  So this is the reason I haven't discovered this bug so far.
* Strange: Tags are also shown when using the VLC player instance from Windows under Arch Linux (via WINE).

So I'm not sure whether the Tag Editor actually produces corrupted file or just files which can not be handled by particular applications.

**Comment by Martchus** [comment]
I found only one bug so far (which might be it). See: https://github.com/Martchus/tagparser/commit/f39d8abcd42a422c4220b123cf740734d046b4e3

Haven't tested it yet (currently not using Windows).

Created a new build which includes this commit: http://martchus.no-ip.biz/repo/win/static/tageditor-devel-3-static-x86_64-w64-mingw32.tar.xz

**Comment by brachna** [comment]
Tested provided new build. Unfortunately Windows explorer still doesn't show tags.

**Comment by Martchus** [comment]
Nice that it works now :-)
