### ISSUE TITLE
Don't know how to change video thumbnail 

### ISSUE THREAD

**Issue by Yoshimit** [Martchus/tageditor#51]
Hi. Trying to change the mkv thumbnail with below command, but Windows 10 do not show it.
I can change the title, but not the thumbnail.
Can you, please, tell me what I'm doing wrong? Thank you.

`tageditor-3.3.2-x86_64-w64-mingw32.exe -s --add-attachment path=Clipboard01.jpg name=thumb desc=thumb mime=image/jpg -f video.mkv`

**Comment by Martchus** [comment]
I don't know what the Windows Explorer expects or supports. Do you have a sample file which works (so I would know what to aim for)?

For MP4 I'm aware that the Explorer simply display the cover art. If the same applies to Matroska the following documentation might help: https://matroska.org/technical/cover_art/index.html

**Comment by Yoshimit** [comment]
thank you the answer.
Turns out that was a Windows 10 bug.
On linux works fine.
