### ISSUE TITLE
Unable to build without GUI on Linux

### ISSUE THREAD

**Issue by natesdot** [Martchus/tageditor#53]
I managed to build tageditor on Ubuntu 19.10 cleanly with the defaults, I was curious how many fewer dependencies there may be if it was built without the GUI, as is there are 147 libraries it is linked against with full GUI. It runs fine from the command line(though so far have only viewed the help haven't actually tried to use it yet)

According to the instructions to build w/o GUI I should use "-DWIDGETS_GUI=OFF -DQUICK_GUI=OFF" with cmake, so I ran this:
`cmake -DCMAKE_BUILD_TYPE=Release -DWIDGETS_GUI=OFF -DQUICK_GUI=OFF -DCMAKE_INSTALL_PREFIX="/usr/local/tageditor"`
(same command line I used before just with the two new options added)

then when I ran make I get this error:

> [ 14%] Building CXX object CMakeFiles/tageditor.dir/application/main.cpp.o
> /home/me/build/tageditor/tageditor-3.3.5/application/main.cpp:25:17: error: ‘QtUtilities’ is not a namespace-name
>    25 | using namespace QtUtilities;
>       |                 ^~~~~~~~~~~
> make[2]: *** [CMakeFiles/tageditor.dir/build.make:63: CMakeFiles/tageditor.dir/application/main.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/tageditor.dir/all] Error 2
> make: *** [Makefile:141: all] Error 2
(not sure how to get the above formatting right, this is my first time creating an issue in github)

I would not expect it to make any calls to Qt stuff if the GUI is disabled?

Not a big deal, just curious.

thanks

**Comment by Martchus** [comment]
I haven't built without GUI recently so it might be broken, indeed. Likely there's just some simple `#ifdef`-wrapping required to make it work again. I can look into it later.

**Comment by natesdot** [comment]
that is the fastest response I have ever seen. thanks so much.

**Comment by Martchus** [comment]
Should be fixed :-)

**Comment by natesdot** [comment]
thanks! Wow I literally am at a loss for words for how quick you responded here. I mean I have been working with Linux and related things since 1996 and have never come across this before. Thanks so much. The non GUI binary seems to want only 7 libraries that is awesome.

**Comment by Martchus** [comment]
You've just reached me when I was programming anyways. By the way, it is possible to build and link against c++utilities and tagparser as static libraries (if you don't do that already). You could produce a fully statically linked binary under GNU/Linux with `-BUILD_SHARED_LIBS=OFF -DSTATIC_LINKAGE=ON -DSTATIC_LIBRARY_LINKAGE=ON`. I only use this configuration to build for Windows so it might not work for Linux (you need all the dependencies as static libraries).

**Comment by natesdot** [comment]
Great! that actually did work fine

~/build/tageditor/tageditor-master$ file tageditor 
tageditor: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=a6de75ce6d1c9f2f468eac0888f494daae340949, for GNU/Linux 3.2.0, not stripped
~/build/tageditor/tageditor-master$ ldd tageditor 
	not a dynamic executable

I was going to resort to using this in a dedicated VM to run, but now I can run it on my regular systems (which are quite a bit older and lack the libc requirements)

thanks!
