### ISSUE TITLE
Accessibility, CTRL + Tab

### ISSUE THREAD

**Issue by NaruFGT** [Martchus/tageditor#59]
When a user is using tageditor with only a keyboard, navigation by using 'Tab' and 'Shift + Tab' seem to be marginally acceptable, until a user navigates to the Lyrics option, where a 'Tab' or a 'Shift + Tab' insert the tab character into the lyrics field.
Most software remedies this with a fairly universal 'CTRL + Tab'  and 'CTRL + Shift + Tab' shortcut to escape the field rather than inserting the tab character.
I'm not familiar with QT but I would imagine this would be configurable by the developer. 
This issue is significant to users who can't operate a mouse or users on devices with limited input capabilities. 
(might be windows only)

**Comment by Martchus** [comment]
I now made the lyrics edit behave like the other edits. Using CTRL as you describe would make sense as well but I haven't found an easy way to enable this behavior in Qt. I suppose not allowing to enter tabs directly is ok.
