### ISSUE TITLE
[Bug] "Encoder settings" field should correspond to ENCODER_OPTIONS rather than ENCODING

### ISSUE THREAD

**Issue by klorax** [Martchus/tageditor#62]
This might be specific to **Opus**, but it stores the "Encoder settings" in the field `ENCODER_OPTIONS` rather than `ENCODING` that _tageditor_ shows.

**Comment by Martchus** [comment]
I'm now wondering myself where I picked up `ENCODING` 6 years ago. It seems that there's `ENCODER` and `ENCODER_OPTIONS` but not `ENCODING` (e.g. on https://exiftool.org/TagNames/Vorbis.html). I'll fix the mapping. When using the CLI you can workaround it by using the native field IDs directly (see README).

**Comment by Martchus** [comment]
Should be fixed by the commit already referenced by GitHub.

**Comment by klorax** [comment]
Yes, it works now!

Thanks for a quick fix and a great tool!
