### ISSUE TITLE
Option to preserve "modification date" does not work under Windows

### ISSUE THREAD

**Issue by blueclouds8666** [Martchus/tageditor#71]
on some occasions it can be useful to keep the original file time and date, for example, audio recordings, so one can still check the original recording date, but that date is gone once the file is modified with Tag Editor (assuming that information was not present in the metadata). i've been checking the GUI and documentation but i have not found such function. it would be a nice addition to have a modifier for such.

**Comment by Martchus** [comment]
There's only a CLI option so far: https://github.com/Martchus/tageditor/issues/66

**Comment by blueclouds8666** [comment]
perhaps it is related to OGG. i've executed the exact same command but for a .mp3 file and it does keep the original timestamp

**Comment by Martchus** [comment]
> i'm on windows, if that could be a factor.

Yes, it is possible that the C++ standard library function I'm using hasn't been implemented correctly on Windows by libstdc++.

> perhaps it is related to OGG. i've executed the exact same command but for a .mp3 file and it does keep the original timestamp

Maybe the mp3 file didn't need a full re-write. Unfortunately with Ogg a full re-write is always required.

---

Note that this flag is only about the modification date but *not* about the creation date (which so far will always be updated if a re-write is required). That's because the C++ standard library doesn't provide a function to set the file creation date, likely because it isn't universally available across all platforms/filesystems.

**Comment by blueclouds8666** [comment]
is there some workaround that can be done? i don't mind about the creation date, only the modification one.

**Comment by Martchus** [comment]
Possibly it isn't supported, indeed: https://github.com/gcc-mirror/gcc/blob/58608f64a76a06fa3652243618f931eed099068f/libstdc%2B%2B-v3/src/filesystem/ops.cc#L923

As a workaround it would of course be possible to use the WinAPI directly or Boost.Filesystem. PRs are welcome.

**Comment by Martchus** [comment]
When running the Windows build with WINE, `--preserve-modification-time` seems to work just fine, also when the file needs to be rewritten. I can give it a try under Windows when booting the OS anyways.

**Comment by Martchus** [comment]
I cannot reproduce the issue under Windows 10. The modification date is preserved when using `--preserve-modification-time` and applying changes to an Ogg/Opus file. As I said before, the creation date is *not* covered by this option yet (and hence will be updated).

**Comment by blueclouds8666** [comment]
I have tested this further with Windows 7, 8.1 and 10 (1607), but the timestamp is not kept.
I have recorded a [small clip](https://mega.nz/file/3GQzBQhS#BziMD1Ym25kJsEiPuBotEOkEGz1nV3bAy2R_Ba2t97I) using the latest stable release so you can see.
However, as you said, it works perfectly fine under Wine (Knoppix 9.1, Wine 5.0).
It could be that the WinAPI implementation only works with newer windows builds?

**Comment by Martchus** [comment]
Not sure what Windows build I had installed when I tested it but likely a quite recent one. It is possible that libstdc++'s `std::filesystem::last_write_time` doesn't work on older Windows versions but somehow I doubt it. It might also be broken if the path contains non-ASCII characters (but it doesn't seem to be the case in your video). In any case, there should actually be an error if preserving the modification data doesn't work but not even an error shows up in your case which is quite unexpected.

In the video it doesn't look like you're refreshing the explorer's view. Maybe it helps pressing F5? It is possible that the explorer catches the new file being automatically but needs a manual refresh for the updated modification time.

**Comment by Martchus** [comment]
It looks like they use `_wutime` and `_wstat64`, see  https://github.com/gcc-mirror/gcc/blob/58608f64a76a06fa3652243618f931eed099068f/libstdc%2B%2B-v3/src/filesystem/ops-common.h#L104 and https://github.com/gcc-mirror/gcc/blob/58608f64a76a06fa3652243618f931eed099068f/libstdc%2B%2B-v3/src/filesystem/ops.cc#L918 and https://github.com/gcc-mirror/gcc/blob/58608f64a76a06fa3652243618f931eed099068f/libstdc%2B%2B-v3/src/filesystem/ops.cc#L788 and https://github.com/gcc-mirror/gcc/blob/58608f64a76a06fa3652243618f931eed099068f/libstdc%2B%2B-v3/src/filesystem/ops-common.h#L78

So it looks like it should work, even if the path contains non-ASCII characters.

**Comment by blueclouds8666** [comment]
after refreshing the explorer and cheching the file properties window, the timestamp is the same as shown before, being the original one replaced. i also forgot that in the video, the command line prompt was running without admin privileges, but the issue still happens under the context of admin privileges.

i can try debugging the issue myself for finding the exact cause of the problem, but might take me a while to find time for it. i will let you know once i get hands in it.
