### ISSUE TITLE
Not seeing title of MKV movie

### ISSUE THREAD

**Issue by Taomyn** [Martchus/tageditor#72]
Using the app, v3.4.3 (Win10), I only see this:

![image](https://user-images.githubusercontent.com/4365929/130346875-f0f7f6df-6ab8-4cec-bcb0-4e78c97b2aaa.png)

There does not appear to be a saved movie title, however both MediaInfo and VLC see this:

![image](https://user-images.githubusercontent.com/4365929/130346914-f20f798d-6afd-4e9f-b7ad-16e0f450e1f5.png)

![image](https://user-images.githubusercontent.com/4365929/130346940-abf95bd9-d22d-4a83-b18e-a8102957a8cd.png)

`{
"media": {
"@ref": "M:\\Video\\Movies\\The Suicide Squad.mkv",
"track": [
{
"@type": "General",
"UniqueID": "127477036689460474603622278337911707008",
"VideoCount": "1",
"AudioCount": "1",
"TextCount": "3",
"FileExtension": "mkv",
"Format": "Matroska",
"Format_Version": "4",
"FileSize": "8910755824",
"Duration": "7926.656",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "8993206",
"FrameRate": "23.976",
"FrameCount": "190049",
"StreamSize": "2118685",
"IsStreamable": "Yes",
"Title": "The Suicide Squad (2021)",
"Movie": "The Suicide Squad (2021)",
"Encoded_Date": "UTC 2021-08-05 22:55:41",
"File_Created_Date": "UTC 2021-08-06 00:04:56.272",
"File_Created_Date_Local": "2021-08-06 02:04:56.272",
"File_Modified_Date": "UTC 2021-08-05 23:15:24.680",
"File_Modified_Date_Local": "2021-08-06 01:15:24.680",
"Encoded_Application": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
"Encoded_Library": "libebml v1.4.2 + libmatroska v1.6.4",
"extra": {
"IMDB": "tt6334354",
"TMDB": "movie/436969"
}
},
{
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": "15780911872058152804",
"Format": "AVC",
"Format_Profile": "High",
"Format_Level": "4",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "4",
"CodecID": "V_MPEG4/ISO/AVC",
"Duration": "7926.627000000",
"BitRate_Mode": "VBR",
"BitRate": "8250000",
"BitRate_Maximum": "12374976",
"Width": "1920",
"Height": "1080",
"Stored_Height": "1088",
"Sampled_Width": "1920",
"Sampled_Height": "1080",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "23.976",
"FrameCount": "190049",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"Delay": "0.000",
"StreamSize": "8147523780",
"Encoded_Library": "x264 - core 157 r2965 861cec4",
"Encoded_Library_Name": "x264",
"Encoded_Library_Version": "core 157 r2965 861cec4",
"Encoded_Library_Settings": "cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=34 / lookahead_threads=5 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=96 / keyint_min=96 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=8250 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=12375 / vbv_bufsize=6187 / nal_hrd=vbr / filler=0 / ip_ratio=1.40 / aq=1:1.00",
"Default": "Yes",
"Forced": "No",
"BufferSize": "6186992",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.709",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "BT.709",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.709",
"matrix_coefficients_Source": "Stream"
},
{
"@type": "Audio",
"StreamOrder": "1",
"ID": "2",
"UniqueID": "3555618506355815202",
"Format": "E-AC-3",
"Format_Commercial_IfAny": "Dolby Digital Plus with Dolby Atmos",
"Format_Settings_Endianness": "Big",
"Format_AdditionalFeatures": "JOC",
"CodecID": "A_EAC3",
"Duration": "7926.656000000",
"BitRate_Mode": "CBR",
"BitRate": "768000",
"Channels": "6",
"ChannelPositions": "Front: L C R, Side: L R, LFE",
"ChannelLayout": "L R C LFE Ls Rs",
"SamplesPerFrame": "1536",
"SamplingRate": "48000",
"SamplingCount": "380479488",
"FrameRate": "31.250",
"FrameCount": "247708",
"Compression_Mode": "Lossy",
"Delay": "0.000",
"Delay_Source": "Container",
"StreamSize": "760958976",
"StreamSize_Proportion": "0.08540",
"Language": "en",
"ServiceKind": "CM",
"Default": "Yes",
"Forced": "No",
"extra": {
"ComplexityIndex": "16",
"NumberOfDynamicObjects": "15",
"BedChannelCount": "1",
"BedChannelConfiguration": "LFE",
"bsid": "16",
"dialnorm": "-29",
"compr": "-0.28",
"acmod": "7",
"lfeon": "1",
"dialnorm_Average": "-29",
"dialnorm_Minimum": "-29",
"compr_Average": "2.25",
"compr_Minimum": "0.53",
"compr_Maximum": "4.54",
"compr_Count": "181"
}
},
{
"@type": "Text",
"@typeorder": "1",
"StreamOrder": "2",
"ID": "3",
"UniqueID": "18219669403594586881",
"Format": "UTF-8",
"CodecID": "S_TEXT/UTF8",
"Duration": "7886.000000000",
"BitRate": "42",
"FrameRate": "0.169",
"FrameCount": "1335",
"ElementCount": "1335",
"StreamSize": "41551",
"Title": "English",
"Language": "en",
"Default": "No",
"Forced": "No"
},
{
"@type": "Text",
"@typeorder": "2",
"StreamOrder": "3",
"ID": "4",
"UniqueID": "9952640545221721601",
"Format": "UTF-8",
"CodecID": "S_TEXT/UTF8",
"Duration": "7886.000000000",
"BitRate": "61",
"FrameRate": "0.260",
"FrameCount": "2051",
"ElementCount": "2051",
"StreamSize": "60945",
"Title": "English CC",
"Language": "en",
"Default": "No",
"Forced": "No"
},
{
"@type": "Text",
"@typeorder": "3",
"StreamOrder": "4",
"ID": "5",
"UniqueID": "14940999155439593855",
"Format": "UTF-8",
"CodecID": "S_TEXT/UTF8",
"Duration": "7890.583000000",
"BitRate": "52",
"FrameRate": "0.234",
"FrameCount": "1849",
"ElementCount": "1849",
"StreamSize": "51887",
"Language": "es",
"Default": "No",
"Forced": "No"
}
]
}
}
`

Is this something tageditor cannot show/edit?

[TheSuicideSquad.html.txt](https://github.com/Martchus/tageditor/files/7026762/TheSuicideSquad.html.txt)

**Comment by Martchus** [comment]
Considering VLC's dialog, it looks like the field your file's title is specified with is `Title`. That's a non-standard tag and the GUI currently doesn't allow to show/edit those. The CLI should show the tag via `tageditor get --show-unsupported -f …` and also allows to set custom fields (see README.md).

The standard field name would be `TITLE` (all letters are upper case). Currently the tag editor is case-sensitive when distinguishing Matroska tag field. I'm not sure whether Matroska tags are actually case-insensitive because the [specification](https://matroska.org/technical/tagging.html) doesn't say much about it. It only says that all tag names should be capitalized but not whether different casings should be treated equal or not.

**Comment by Taomyn** [comment]
So it seems that both MediaInfo and VLC must be uppercasing all tag names regardless, especially as the spec does state they are all meant to be uppercase - I suspect they both hit this issue as well some time in the past.

You are correct that running the CLI with those parameters did show the tag, but I'm not familiar with running it that way. How would I use the CLI to simply remove those tags?

What I did do and seems to have worked is used the "Delete all tags" button on the GUI on that file and now I no longer see them. The main reason I use tageditor is to clear out badly entered fields, mostly the TITLE one as it causes issues with the movie scrapers in Kodi - for some reason those tags override the file name, which is fine, but there is no method to then tell Kodi to override that, so when someone has entered the title as "Wibble" that's all it will ever scrape for no matter what you do. Your tool has been very useful in fixing my files.

**Comment by Martchus** [comment]
I've been asking on #matroska IRC. In conclusion I suppose I should make it convert everything to upper case, or at lest known field names and with an opt-out. This would improve the standard compliance as the tag editor would ensure upper case field names (which are recommended) and also work around being unable to read lower-case but otherwise standard tags.

The CLI can remove those tags like this: `tageditor set --remove-other-fields -f …`

"Delete all tags" in the GUI is expected to work, indeed. It just deletes all tags, including those which are unknown to the tag editor.

**Comment by Martchus** [comment]
By the way, which application did you use to create the Matroska file? The fact that it is writing tags in a way which is explicitly *not* recommended by the standard might be worth creating an issue there. At least I don't see a good reason for not following the standard's recommendation here.

**Comment by Martchus** [comment]
Closing as it should be fixed now.
