### ISSUE TITLE
Error Unable to assign attachments because the container object has not been initialized

### ISSUE THREAD

**Issue by hunandy14** [Martchus/tageditor#74]
I want to use the command to change the thumbnail, what should I do？
(graphical interface can be successfully changed.)

thank you

![image](https://user-images.githubusercontent.com/13827054/134697663-c4033c5f-e468-4032-8b07-8c2197566077.png)

**Comment by Martchus** [comment]
The error message is certainly confusing but I'm afraid you cannot set attachments in MP4 files in general. Attachments are in fact only implemented for Matroska files and I don't think the MP4 format itself supports attachments anyways. If you would like to set a cover, just set it as tag value. The cover should then also be recognized by other applications.

**Comment by Martchus** [comment]
By the way, there's already https://github.com/Martchus/tageditor/issues/55 which is about streamlining adding covers to Matroska files so one could also add a cover to Matroska file by setting the tag value and would not have to use different commands depending on the file format. However, I have not implemented it yet.

**Comment by hunandy14** [comment]
> If you would like to set a cover, just set it as tag value.

What i want to do is this.
![image](https://user-images.githubusercontent.com/13827054/134701260-471a6744-c2a0-4c01-8a8d-8637a5d8a36b.png)

can give me an Command line example?

**Comment by Martchus** [comment]
Something like `tageditor set cover=/the/cover.jpg -f /the/file.mp4` should work. Also checkout `--help` and the README.

**Comment by hunandy14** [comment]
succeeded!!!
thank you very much. ♪(´▽｀)♪(´▽｀)♪(´▽｀)

**Comment by Martchus** [comment]
Glad to help and I guess I should improve the error message.
