### ISSUE TITLE
Installs to usr/local/bin/bin on a Mac

### ISSUE THREAD

**Issue by buckmanhands** [Martchus/tageditor#78]
Hi, pretty much the title.

the tageditor executable ended up in the `usr/local/bin/bin`

note the extra bin.

This truly could be a problem between my keyboard and my chair, but I figured I would point it out. I really don't know enough to track this down. Only bit of info I can give is my cMake command, which worked like a charm otherwise and I just moved the executable up one bin and the program works great.

```
cmake ENABLE_THREAD_LOCAL=OFF  \
USE_STANDARD_FILESYSTEM=OFF \
-DCMAKE_CXX_FLAGS="-std=c++17" \
-DCMAKE_BUILD_TYPE=Release \
-DWIDGETS_GUI=OFF \
-DQUICK_GUI=OFF \
-DCMAKE_INSTALL_PREFIX="/usr/local/bin" \
"~/Desktop/tageditor/tageditor/"
```

This is the end of my bug report, but I wanted to throw a bone to others trying to compile this on a Mac (or hackintosh):

Some notes for others trying to get this compiled on Mac OS Big Sur:

Compile cpp-utilities first, then tagparser, then tageditor. Be absolutely sure you have xcode command line tools up to date. I installed them right before installing tageditor and they were not up to date and I failed the std::filesystem test no matter what I did to force c++17 instead of c++11. I ran `brew doctor` and it told me my xcode commandline tools were outdated and showed me the command to update them. Then everything worked. I also uninstalled Xcode.app (since I just use the CLT anyways) but I am not sure if that made any difference.

I was never able to get the installers to see OpenSSL or cppunit, even though I had them both installed and in my $PATH, but the programs compiled without it and I didn't look further into why.

There were two errors in tagparser that I needed to fix before it would compile (these may be mac only things):

1. In the file `generate_iso_language_codes.cmake` a line looks for a file in the `usr/share` directory, it is in `usr/local/share`... you will need to edit that path.

2. tagparser/mpegaudio/mpegaudioframe.cpp:55:123
This line throws an error: use of overloaded operator '-' is ambiguous
I just made the line (which is a line that writes an error message, ironically) into a line of static text. Not ideal, since the error is now generic, but it makes the error go away and the package will then compile. If you know how to fix it, you should make a pull request or offer it up to the devs here. I would have, but I didn't know how.

Once I got all three packages compiled (I did it in ZSH and Bash, both worked) I had to quit the terminal and start a new ZSH session to get all of the tageditor functions to work properly.

**Comment by Martchus** [comment]
I haven't had time to read it all but that's expected behavior considering you specified `-DCMAKE_INSTALL_PREFIX="/usr/local/bin" \`. Leave off the `bin` here.

**Comment by Martchus** [comment]
Note that `-DCMAKE_CXX_FLAGS="-std=c++17" \` should not be required as well because the CMake build file sets the expected version on its own (in a platform independent way).

---

OpenSSL and cppunit are only required by the tests so you can live without them. Note that it isn't only required to have the OpenSSL executable in the path because the tests need the underlying libraries and header files. Just look at CMake's documentation about dependency lookup as my build script just users the normal find module mechanisms.

---

Note that for one of my other projects one created a package on MacPorts: https://ports.macports.org/port/syncthingtray/
I suppose the same would make sense for the tag editor as well.

**Comment by buckmanhands** [comment]
For the /bin/bin issue, I suppose that is why the two dependencies cpp-util and tagparser ended up in usr/local/bin/share. I suppose they  should actually be in usr/local/share. Thank you... I am a noob at compiling things manually. Too reliant on Homebrew. I will try recompiling it all properly.

RE: -DCMAKE_CXX_FLAGS="-std=c++17": In the error log it showed that the compiler was choosing c++11 in some of it's logging I think. Also, I think this is more of a Mac issue that many others faced when compiling, it seems that xCode does some very painful things for people. But I am a noob, so it could definitely be a problem between the keyboard and the chair.  Maybe also it was because I installed the dependencies in the wrong place. When I reinstall to get all the paths right I will send along the error log so you can see what cpp-utilities is choosing.

Thanks for the program, it seems to work pretty well.

**Comment by buckmanhands** [comment]
I redid the install using your ninja method and it all installed great, with the exception of reflection RapidJSON. It seems that install could not find clang. Could be a mac thing. I installed the GUI too, just to have a look at it.

I can look into getting you the errors, but essentially it was a whole heap of file not found errors, and I went and looked but they were all where they should be that I could tell.

In general, the main difficulty I was having was not adding -D to the beginning of a lot of the cmake flags. In your documentation you leave it off a lot and then other times use it, so I really did not know what I was supposed to put (me noob, unga bunga). Here was my final cmake command. All things in here were essential, but I did not need a couple of the things you said a Mac would need. I installed all the packages separately before trying the ninja method and played around with all the flags to see what was essential.


`cmake \`
`-G Ninja \`
`-DENABLE_THREAD_LOCAL=OFF \`
`-DCMAKE_BUILD_TYPE=Release \`
`-DCMAKE_CXX_FLAGS="-std=c++17" \`
`-DWEBVIEW_PROVIDER:STRING=webengine \`
`-DJS_PROVIDER:STRING=script \`
`-DLANGUAGE_FILE_ISO_639_2="/usr/local/share/iso-codes/json/iso_639-2.json" \`
`-DCMAKE_INSTALL_PREFIX="/usr/local" \`
`"~/Desktop/myfiles/subdirs/tageditor"`

-DCMAKE_CXX_FLAGS="-std=c++17" was essential, or it would error out.

I wish I would have taken better notes on all the dependencies I installed (it was a lot, thankfully 99% were homebrew so I may be able to figure it out and provide a clean list here later).

All previous issues in this thread were figured out and likely due to quirks on a mac. OpenSSL, cppunit, all function now.

**Comment by Martchus** [comment]
For reflective-rapidjson you actually need clang's underlying libraries (not the compiler itself). Maybe that's not installed yet on your system. Note that this is just for the JSON export which is a feature that's likely not that useful anyways so you can likely just leave it off.

Since you're already using homebrew it would make sense to create a homebrew package/formula/recipe or however they call it for the tag editor itself. That would enclose all the details you've just mentioned in a single build script everybody can easily invoke. It could also be referenced in the README like the packaging files that are already mentioned there for other platforms.

**Comment by buckmanhands** [comment]
Once I iron out all of these details I do hope to create a homebrew formula (trying to compile a concide dependency list right now). Though, your build it all at once ninja method is quite good and fast. Having it in Homebrew would allow for easy package management though.

I actually would really like the option to export as json as it will help my long term goals.

It seems you are correct that the xCode clang does not have the underlying libraries I need, but I can find all the files that are coming up with file not found errors here (my homebrew llvm install):

`/usr/local/Cellar/llvm/13.0.0_2/include/clang/AST/DeclCXX.h` as an example. 
This is the first one that fails when this line in codegenerator.cpp is called at line 6:
`#include <clang/AST/DeclCXX.h>`

However, I can't seem to get the homebrew clang/llvm to be involved in the compiling. If you have any suggestions on cmake flags I can set to force this, I would be grateful. Nothing I have tried works and I do have homebrew llvm in my path. This is a special kind of pain that apple xcode inflicts and there are numerous stackoverflow questions about it but none seem to have a concise answer that works, many just say it is impossible.

**Comment by Martchus** [comment]
For CMake to find the Clang *library* you also need the CMake module for it installed, e.g. on a GNU/Linux distribution you would have the following files installed:
```
/usr/lib/cmake/clang/AddClang.cmake                                                                                                                      
/usr/lib/cmake/clang/ClangConfig.cmake                                                                                                                   
/usr/lib/cmake/clang/ClangTargets-release.cmake                                                                                                          
/usr/lib/cmake/clang/ClangTargets.cmake
```

**Comment by buckmanhands** [comment]
Thanks. I just want to see how json response works. And a lot of this is just a learning experience as I delve into the command line and scripting. I have written web code (php and javascript mostly) for ages and want to expand my knowledge. Mostly I learned that all would be better if I finally just went fully linux.

I have everything in tageditor working now and even got qt and the GUI up and running. Now I am playing around and looking code side at how things work. I may want to delve into adding a feature or two for the command line. Here are some things that would be nice to have:

1. On the `get` info, a feature that was quieter, like it literally only passed back the value (or name value pair) of the request or false.
2. A has-artwork sniffer that just pushed back true/false. Right now I have to parse the response to check if it ends with 'none'.
3. In the GUI, the file browser won't show a doc tree of an external volume where all my music is.
4. When grabbing the artwork from an online source (I use deezer from the CLI to get them) to push it straight from a variable into the file (similar to the feature request you already have for a web address image path), but I already have a cli script to get the image and storing it in a variable.
5. Auto-deletion of the .bak files. It was something in AtomicParsley that was nice, but theirs left an album cover behind with a random string name.

I would love to start with #2, can you point me in the direction of the files/functions I would need to edit to add a --hasart flag to the CLI version? I will be happy to push the changes back to you and you can add it if you like. I just want to try my hand at coding a CLI program.

**Comment by Martchus** [comment]
I suppose 1. and 2. would also easily be solved by using the JSON export (maybe the JSON export needs still some improvement). It seems better to simply support a machine readable format for such cases instead of adding various additional tweaks to the normal output which is mainly intended for human readers. Besides, multiple files can be specified, even a single file might contain multiple tags and a single field might contain multiple values. So it isn't generally possible to boil it down to a single return value. The cover shouldn't also be treated more different compared to other fields than necessary. Note that you can read single values from JSON easily via `jq`. Btw, I didn't put much effort into this yet because I'd personally just write a small C++ program using the underlying library directly. That's of course not very convenient for everybody.

Note that 3. isn't the case under GNU/Linux (where it simply shows the file system tree) and also not under Windows (where it shows all drive letters). The tree is simply using `QFileSystemModel` so this seems to be a limitation of that Qt-provided class then. If you're not using Qt 6 already you could try upgrading first. If it is still broken it might make sense to fix it within Qt itself. (But of course check before whether my code isn't messing with the model after all.)

Not sure whether I understand 4. correctly.

I've never implemented an auto-deletion for backup files because I usually simply specify a backup directory and clean it up after I'm sure I don't need it anymore. Or I'm using the renaming utility to move files separating backup files by the way. Or I simply use `find . -name '*.bak' -delete` or something similar to get rid of them.

**Comment by Martchus** [comment]
But for the sake of simplicity the following feature might make sense:

```
$ tageditor get --simple-format title artist album cover -f /some/file /another/file
The Title of /some/file
The Artist of /some/file

binary
The Title of /another/file
The Artist of /another/file
The Album of /another/file

```

So it would emit exactly one line for each specified field with the most relevant¹ field value found in the file. An empty line line is written if the field does not exist or is empty.

¹ e.g. ID3v2 takes precedence over ID3v1

---

Alternatively one could also add a scripting feature utilizing the JavaScript engine provided for the renaming utility, e.g.:

```
$ tageditor run --script "return tageditor.parseFileInfo(tageditor.currentPath).tag.cover !== undefined" -f /some/file /another/file
[true, false]
```

The tag object would also contain the most relevant information here (like it is already done for the renaming utility). This approach would be a bit cumbersome to use but also very powerful as one could write arbitrary JavaScript and return arbitrary JavaScript/JSON objects. It would even be possible to expose a function for saving changes.

**Comment by buckmanhands** [comment]
1 & 2. Yeah, I thought the same, if I had the json then I could more easily parse this data reliably.
As for having a --hasartwork flag that is nice to easily script if I should go find the artwork or move on to the next file. So I thought adding a CLI option such as `tageditor -g --hasartwork -f path/to/file.mp3` (returns true/false) would be a good way for me to learn how to add code to an existing project and how a CLI program is made.

3. I started with qt6 and installation of tageditor threw errors saying it wanted qt5, so I installed qt5 and then tageditor installed without error. Maybe I did something wrong, so I will try installing qt6 again and see if I can reinstall tageditor. Mostly, I am just using the GUI to see if my script is working to change files so not a huge deal, I can use file->open to view a file I manipulated on an external drive. It could be all of Mac's new security, I have to approve some programs reading files on an external drive randomly via a popup now :/

4. Well, when I use wget to grab an image from an online source, I store the file contents in a variable rather than write it to a file. Was trying to see if there was a way to pass that to `tageditor -s cover=$mycoverdata -f path/to/file.m4a` - this seems cleaner than creating a file somewhere and then deleting it after I add it (which is easy and I have a working script to do).

RE: autodelete - I already have a way to delete them and I think in the long run it is better to have to script it in later because errors happen and I would hate to accidentally buzzsaw my music collection.

**Comment by buckmanhands** [comment]
I like the `--simple-format` flag. But I would go even simpler and maybe even make it only work if one source file is asked for or put a newline with `~~~~` between the sources. No extra verbage at all. Not even the source file, we obviously already have that information available or tageditor would not be looking. Just return the data in the order provided, both for the fields and the sources.

``
$ tageditor get --simple-format title artist album cover -f /some/file /another/file

Return data:
the title
the artist
the album
the cover (true/false or yes/no or some/none - your current lengthy explanation is probably fine if I can test for none)
~~~~~~
the title
the artist

the cover
``

I am just getting my feet wet in managing music files, and I see the mess they made with multiple versions and multiple tags early on. I suppose there may need to be a separator that does not cause problematic collisions if there are multiple output for a field. Way back I used to pass data from php to javascript without json I used ||| in my data. It was easy to split and caused few collisions:

``
thetitle
the artist|||the second artist
the album
the cover
``

I would be happy to help implement this. I have not written c++, but I have written php and javascript for the last 18 years as a career. If you want help and can provide direction on which files/functions need editing. Maybe some if --simple exists then don't add the human readable cruft and return the output bare, there must be some place where you wrap all that static data around the variables.

**Comment by buckmanhands** [comment]
Sorry, this thread has a lot going on, if there is a better way I am happy to move this part to a reflective issue

I looked and in the cmak clang module 
[CMakeCache.txt](https://github.com/Martchus/tageditor/files/7706282/CMakeCache.txt)
files you speak of are here:
`usr/local/opt/llvm/lib/cmake/clang`

I also looked in the cMakeCache.txt file and it shows the following:
```
//The directory containing a CMake configuration file for Clang.
Clang_DIR:PATH=/usr/local/opt/llvm/lib/cmake/clang
```
But when I try to do my install with the following cmake command:
```
cmake \
-G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_FLAGS="-std=c++17" \
-DCMAKE_INSTALL_PREFIX="/usr/local" \
"/Users/oldfaithful/Local/tageditor/reflective-rapidjson"
```
I get a ton of file not found errors that all look similar to this:

```
[1/22] Building CXX object generator/C...ator.dir/clangversionabstraction.cpp.o
FAILED: generator/CMakeFiles/reflective_rapidjson_generator.dir/clangversionabstraction.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -DCPP_UTILITIES_STATIC -DCPP_UTILITIES_USE_STANDARD_FILESYSTEM -DREFLECTIVE_RAPIDJSON_STATIC -I/Users/oldfaithful/Local/tageditor/reflective-rapidjson/generator -I/Users/oldfaithful/Local/tageditor/reflective-rapidjson/build/generator -I/Users/oldfaithful/Local/tageditor/reflective-rapidjson/lib/include -I/usr/local/Cellar/rapidjson/1.1.0/include -isystem /usr/local/include -std=c++17 -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -fvisibility=hidden -MD -MT generator/CMakeFiles/reflective_rapidjson_generator.dir/clangversionabstraction.cpp.o -MF generator/CMakeFiles/reflective_rapidjson_generator.dir/clangversionabstraction.cpp.o.d -o generator/CMakeFiles/reflective_rapidjson_generator.dir/clangversionabstraction.cpp.o -c /Users/oldfaithful/Local/tageditor/reflective-rapidjson/generator/clangversionabstraction.cpp
In file included from /Users/oldfaithful/Local/tageditor/reflective-rapidjson/generator/clangversionabstraction.cpp:3:
/Users/oldfaithful/Local/tageditor/reflective-rapidjson/generator/./clangversionabstraction.h:6:10: fatal error: 'clang/Basic/SourceLocation.h' file not found
#include <clang/Basic/SourceLocation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Martchus** [comment]
> I am just getting my feet wet in managing music files, and I see the mess they made with multiple versions and multiple tags early on.

Yes, it is really a mess. There are so many different container/tag/media formats and creating a tool which is kind of generic is not particularly easy.

> I would be happy to help implement this. I have not written c++, but I have written php and javascript for the last 18 years as a career.

Unfortunately C++ isn't the easiest language to learn and this project is kind of big already. Sometimes I'll have to re-read parts of the code myself to understand again how it works (as I'm not developing all parts of it very regularly). I appreciate that you want to help and it would be great if you could make sense of the code. However, I suppose explaining the code in further detail is a lot of effort. For the right direction I can point you the files in https://github.com/Martchus/tageditor/tree/master/cli and https://github.com/Martchus/tageditor/tree/master/application which contain the sources of the CLI and tests are inhttps://github.com/Martchus/tageditor/blob/master/tests/cli.cpp.

I appreciate that people like to use my software but I must also say that some tasks might be better done with other software. You've already noticed that multi media is a mess - hence there's also no tool to rule them all. E.g. MediaInfo could be helpful in your case. It is more about reading technical information (and is way better in that regard than my tag editor) but can also read basic tags. For instance I sometimes use `mediainfo --Output=JSON /some/file | jq ...` to gather certain information. There's no need to re-invent the whell all the time which is also the reason I've never implemeted certain features in tag editor.

> I get a ton of file not found errors that all look similar to this

There's simply the include path for Clang's header files missing. There should be `-I/usr/local/Cellar/llvm/13.0.0_2/include` somewhere in the compiler invocation according to the path you've previously mentioned. It seems wrong that the CMake find module is localed under `/usr/local/opt` and the 
header files are under `/usr/local/Cellar`. Are you sure these belong to the same installation? Note that you can set variables like `Clang_DIR` also via e.g. `cmake -DClang_DIR=...` to specify the location of a certain library directly (instead of relying on automatic detection).

**Comment by buckmanhands** [comment]
> For the right direction I can point you the files

Thanks I will have a look and see if there is something I can do. I find having a "real" project has spurred me to learn more quickly. This will be a great way to learn even if it is not code you want to add to the package.

> MediaInfo could be helpful in your case.

I will have a look at it. I chose your package because it did handle all the formats I needed and also wrote album covers and had a CLI. I have over 100,000 songs to go through so a script is handy. I had nearly all the album covers and when Apple switched to Music from iTunes almost all of them disappeared and are also no longer embedded.

> There's simply the include path for Clang's header files missing. There should be -I/usr/local/Cellar/llvm/13.0.0_2/include somewhere in the compiler invocation according to the path you've previously mentioned. It seems wrong that the CMake find module is localed under /usr/local/opt and the
header files are under /usr/local/Cellar. Are you sure these belong to the same installation?

These are the same. Homebrew adds symlinks for all of this stuff so you generally never point to the cellar
`/usr/local/Cellar/llvm` = `usr/local/opt/llvm`

Could I put:
`export CPPFLAGS="-I/usr/local/opt/llvm/13.0.0_2/include"`
Into my .zshrc?
And would I combine that with my other CPP_FLAG
`export CPPFLAGS="-I/usr/local/opt/openssl@3/include"`

**Comment by Martchus** [comment]
Better add it to CXXFLAGS. Multiple flags can be specified (separated via a white space). There are also CMake variables you can set to pass flags. But if that's neccassary something is wrong. Maybe the Clang package fails to set the include directory for its imported target.

**Comment by buckmanhands** [comment]
I got reflective-rapidjson installed! As it turns out

`/usr/local/Cellar/llvm =/= /usr/local/opt/llvm`

The symlink in opt skips the enclosing folder that shows the version

`/usr/local/Cellar/llvm/13.0.0_2/include = /usr/local/Cellar/llvm/include`

Without one of the above paths set in my .zshrc using CXXFLAGS my compiling of reflective will fail.

If I have the following flag in my reflective cmake command, the build fails even with the CXXFLAGS in my .zshrc

`-DCMAKE_CXX_FLAGS="-std=c++17"`

However, it does work if I also add the above path in my cmake command (weird):

`-DCMAKE_CXX_FLAGS="-std=c++17 -I/usr/local/opt/llvm/include"`

So I went ahead and removed the CMAKE_CXX_FLAGS from the cmake command and got `reflective-rapidjson` installed :)

Unfortunately, when I try to install tageditor with reflective-rapidjson enabled I get errors related to reflective and it makes the install fail

my cmake (it fails sooner unless I force std=c++17):
```
cmake \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_FLAGS="-std=c++17" \
-DWIDGETS_GUI=OFF \
-DQUICK_GUI=OFF \
-DENABLE_JSON_EXPORT=ON \
-DREFLECTION_GENERATOR_EXECUTABLE="/usr/local/bin/reflective_rapidjson_generator" \
-DCMAKE_INSTALL_PREFIX="/usr/local" \
"/Users/oldfaithful/Local/tageditor/tageditor"
```

The error
```
/usr/local/include/rapidjson/document.h:1756:106: error: no member named 'Set' in 'rapidjson::internal::TypeHelper<rapidjson::GenericValue<rapidjson::UTF8<>>, unsigned long>'
    ValueType& Set(const T& data, AllocatorType& allocator) { return internal::TypeHelper<ValueType, T>::Set(*this, data, allocator); }
                                                                                                         ^
/usr/local/include/reflective_rapidjson/json/./reflector.h:154:11: note: in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8<>>::Set<unsigned long>' requested here
    value.Set(reflectable, allocator);
          ^
/usr/local/include/reflective_rapidjson/json/./reflector.h:397:5: note: in instantiation of function template specialization 'ReflectiveRapidJSON::JsonReflector::push<unsigned long, nullptr>' requested here
    push(reflectable, genericValue, allocator);
    ^
/Users/oldfaithful/Local/tageditor/tageditor/build/reflection/json.h:40:5: note: in instantiation of function template specialization 'ReflectiveRapidJSON::JsonReflector::push<unsigned long, nullptr>' requested here
    push(reflectable.size, "size", value, allocator);
    ^
```
