### ISSUE TITLE
[Question] How to get the cover type in console?

### ISSUE THREAD

**Issue by Mapaler** [Martchus/tageditor#82]
![1647432572384_foobar2000](https://camo.githubusercontent.com/caab49c055563ae438770a789208c157d2ca95ca53e921adba22782ac6c86679/687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f36633834623264366777316631336d786b783167346a32316b773077306a7a622e6a7067)
My car MMI system has limited support for music covers.
Must be MP3->ID3->Front Cover->JPEG->Not Progressive JPEGs.

So I now need to move other types of images to the front over. Most of the songs I download are like this.
![1647432572384_foobar2000](https://user-images.githubusercontent.com/6565860/158586850-f5c87c7c-9b4a-4d4d-bfa4-4b3caff57409.png)

Now I've only looked at these core codes.
```bat
tageditor extract cover --output-file the-cover.jpg --file "あよ - 蛙楽.mp3"
:: Some image format conversion codes

tageditor set cover= cover0=""the-cover.jpg:front-cover:封面图片"" --files "あよ - 蛙楽.mp3"
```

How do I monitor if an image is already on the front cover? That way I can make no changes to the audio file.
How do I get this picture in what image format? Tageditor currently displays png normally but MMIE type is displayed as jpeg.
![1647433127762_tageditor](https://user-images.githubusercontent.com/6565860/158588270-88291e4e-5a84-4208-8f60-43e57b4e97b6.png)

**Comment by Martchus** [comment]
The CLI prints something like this:

```
tageditor-qt6 get cover -f "Ace Attorney/2015 - The Great Ace Attorney 1 OST/Disk 2/Ace Attorney, The Great Ace Attorney 1 OST, 2-24 - Musical Box ~ Great Detective of the Foggy Town.mp3"
Tag information for "Ace Attorney/2015 - The Great Ace Attorney 1 OST/Disk 2/Ace Attorney, The Great Ace Attorney 1 OST, 2-24 - Musical Box ~ Great Detective of the Foggy Town.mp3":
 - ID3v1 tag
    Cover             none
 - ID3v2 tag (version 2.3.0)
    Cover (front-cover) can't display as string (see --extract)
```

So you could easily grep for `front-cover` within the output. Maybe that feature isn't present in 3.5.0 yet.

I don't think you can query the MIME-type specified within the tag field via the CLI at this point. Note that the MIME-type specified in the tag must not necessarily match the actual image format. If they divert that could explain why different apps show different types. (Of course that's a mistake but inconsistencies can happen and the Tag Editor also does not prevent you from putting a wrong MIME-type there; the GUI only *suggests* a certain MIME-type after selecting an image.)

By the way, you can easily determine the *actual* MIME-type with the help of the `file` utility:

```
tageditor-qt6 extract cover -f "Ace Attorney/2015 - The Great Ace Attorney 1 OST/Disk 2/Ace Attorney, The Great Ace Attorney 1 OST, 2-24 - Musical Box ~ Great Detective of the Foggy Town.mp3" | file --brief --mime-type -
```

**Comment by Martchus** [comment]
The "can't display as string" part merely means that there *is* a cover bug it won't be printed on the terminal (and one should instead use `--extract` get the image data).

Note that `find` (and `bash`) can be easily installed on Windows via MSYS2. (Although I of course recommend giving Linux a try as development environment.)

**Comment by Mapaler** [comment]
This TagEditor is not going to through the **stdout**?
Neither cmd nor powershell can get the output value.
![cmd_OSi8TfrZ6S](https://user-images.githubusercontent.com/6565860/158638681-df42ef1d-5a94-460a-80ef-9c70d408ce69.png)
![WindowsTerminal_j9aUD1Zwmn](https://user-images.githubusercontent.com/6565860/158637080-702dd82f-0fba-40b8-9c95-c69ca32495e2.png)

**Comment by Martchus** [comment]
Again, have a look at https://github.com/Martchus/tageditor#windows-specific-issues. Basically, you need to set `set ENABLE_CONSOLE=0`.

**Comment by Mapaler** [comment]
I didn't understand the significance of this setup before. I thought it was to modify the settings of cmd.
Is this really just setting a temporary environment variable?

In cmd I successfully redirected to the txt file.
![cmd_Hi2jmtt1za](https://user-images.githubusercontent.com/6565860/158645320-166b0b5b-c17e-4952-8b39-171d884639c9.png)

But tried powershell to capture the variable, it was unsuccessful.
![powershell_AWYRlGE33l](https://user-images.githubusercontent.com/6565860/158644893-801e49b8-86ba-48c5-92ee-ef414a1f1045.png)

Also successfully redirect to a file.
![powershell_uenDm82VgN](https://user-images.githubusercontent.com/6565860/158645937-21d6bc60-8fe1-4a6f-a54f-d51020fbc348.png)

After testing, it can be successfully captured by stdout, which should allow me to use it.
![Notepad2_NkWQrXfWI1](https://user-images.githubusercontent.com/6565860/158648678-c7f90fee-67bc-4cf1-99a6-18c77f9a52dd.png)

**Comment by Martchus** [comment]
Yes, it is really just setting the environment variable. How to do it depends of course on the shell (or however you execute the process).

A long time since I've seen `new ActiveXObject(…)` calls :-)

**Comment by Mapaler** [comment]
Windows Script Host (VBS/JScript) is the most convenient and simple Scripting language on Windows.
There is no need to install additional runtimes from XP to Win11. No additional permission management is required.
The syntax is closer to general programming than powershell.

If you need to write to the average person who does not install the runtime, WSH is very suitable for rapid development.
