### ISSUE TITLE
Command-line exit codes

### ISSUE THREAD

**Issue by 11xx** [Martchus/tageditor#83]
Hi,

The command-line errors don't seem to return exit codes other than `0`.

This shell syntax don't work:

    tageditor extract cover -f "file" -o out.jpg || echo "Error"

I'm using this in a script and the only way to execute commands on
the case `tageditor` errors out is to grep for specific strings.

Also the error strings go to `stout` rather than `sterr`.

Thank you.

**Comment by Martchus** [comment]
Note that there will be generally a non-zero exit code in case there's an error, e.g. if invalid CLI args have been specified. I make the error case "None of the specified files has a (supported) cover field." and similar error cases return a non-zero exit code that is different from the invalid args case.

Note that errors are already generally logged to stderr. The only exception are diagnostic messages (which can be warnings, errors but also just additional information). Maybe these should also be generally printed to stderr. Maybe the error message you want to be printed on stderr instead on stdout is just one of those diagnostic messages. To be sure, what error are you talking about exactly?

**Comment by Martchus** [comment]
Should be fixed on master.

**Comment by 11xx** [comment]
> Note that errors are already generally logged to stderr. The only exception are diagnostic messages

Got it. That's fine then.
It's working great now! Thank very much :+1:
