### ISSUE TITLE
Support rating tag for MP3 and Opus

### ISSUE THREAD

**Issue by stax76** [Martchus/tageditor#84]
MP3 has no official rating support, but MediaMonkey, MusicBee, Strawberry Music Player, Windows File explorer and probably many other apps have agreed on a compatible convention, so it would make sense to support it in this way.

**Comment by Martchus** [comment]
If you could just tell me what the convention looks like (or send me a link to the specification or an example file) that should be easy to implement. I assume Strawberry Music Player means taglib? So if you cannot find any technical details I could still do some testings with that and also dig into taglib's code.

**Comment by Martchus** [comment]
Oh, you're the author of StaxRip. I used that myself some years ago :-)

**Comment by stax76** [comment]
Sample file:

[Koan - Selena's Song (Blue Mix).zip](https://github.com/Martchus/tageditor/files/8910665/Koan.-.Selena.s.Song.Blue.Mix.zip)

**Comment by Martchus** [comment]
Ok, I suppose I remember the POPULARIMETER from reading the ID3v2 standard. It is just not implemented yet.

**Comment by Martchus** [comment]
While the tag field is standard, the string representation with the `|`-separator is "custom". However, it seems other tools already use it as well so I'll be using it as well. I started implementing it. It'll likely be ready for the next release.

**Comment by stax76** [comment]
Thank you.

I've also many Opus files from YouTube, it seems that is commonly handled with the Vorbis comment RATING using a 0-100 scale.

https://github.com/quodlibet/quodlibet/issues/3533

**Comment by Martchus** [comment]
Then it makes sense to implement it in Vorbis comments as well. However, I'm currently still implementing the ID3v2 field which is a bit more involved as it actually also supports a user and a play counter.

I suppose I'll likely will allow editing the string value in the format you've mentioned within the CLI and GUI which will allow you to edit the raw rating value. Implementing a selector with stars that internally sets an appropriate rating value for the current tag format would make sense as well but that's of course also more work.

**Comment by Martchus** [comment]
It is implemented on master for ID3v2 and Vorbis comments. So the field can be edited as string value. If you want to test it, make sure you also have the latest commits from https://github.com/Martchus/tagparser.

**Comment by Martchus** [comment]
Closing as there was no further response.

**Comment by stax76** [comment]
Thanks for the new feature and the new release.
