### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [Martchus/tageditor#88]
As of [version](https://github.com/Martchus/tageditor/releases) [3.7.4](https://github.com/Martchus/tageditor/releases/tag/v3.7.4) [Tag Editor](https://github.com/Martchus/tageditor) saves its configuration file (**tageditor.ini**) in AppData:

`C:\Users\User\AppData\Roaming\tageditor.ini`

For fully and truly portable mode I suggest that when the program starts it checks its program folder (the folder containing the executable) for its configuration file (**tageditor.ini**) and if found it is used (settings are loaded from it and saved to it) without creating a new one is AppData. This will mean that [Tag Editor](https://github.com/Martchus/tageditor) is running in portable mode as it is not writing any data outside its program folder.

I suppose that this will not be hard to be implemented.

Off-topic- thanks to the developer (@Martchus) for offering **Qt5** builds which means that I can still use the program.

**Comment by Martchus** [comment]
Good idea, implemented on master.

> Off-topic- thanks to the developer (@Martchus) for offering Qt 5 builds which means that I can still use the program.

Good to know that there are still users. I suppose I'll retain Qt 5 support for the foreseeable future (and also continue providing builds).

**Comment by smaragdus** [comment]
@Martchus 

> Good idea, implemented on master.

This was impressively quick, thanks!

> Good to know that there are still users. I suppose I'll retain Qt 5 support for the foreseeable future (and also continue providing builds).

This is excellent news for me. I will keep using Windows 7/8/8.1 as long as I can (I have even an XP machine for retro gaming). I refuse to upgrade to Windows 10/11 (for me this would be a downgrade actually) and there are both practical (1) and ideological (2) reasons for this: (1) using stable, heavily customized software that runs smoothly and is not endangered by buggy updates, features removal and heavy bloat is fun; (2) I refuse to accept adware, spyware and forced updates by M$, for me Windows 10/11 are an ugly, unbearable mess. I suppose that in the future I will have to switch to Linux or BSD and also learn to compile stuff myself (I am not a programmer but some days ago I had a peep at Lazarus IDE and I am glad that despite the intimidating interface I managed to compile my first program). I thinks it was a bad idea that Qt 6 had cut off Windows 8.1 support before the official OS support ended.

I did just a brief, superficial testing of [Tag Editor](https://github.com/Martchus/tageditor), liked it and kept it. When I have time I will do some more thorough tests and if it happens that I can think of possible improvements or encounter problems I will let you know.

Thanks for your good tag editor and for the extended support for outdated Windows versions.

Regards

**Comment by smaragdus** [comment]
@Martchus 

I have just tested version [3.7.5](https://github.com/Martchus/tageditor/releases/tag/v3.7.5) and it works as expected- the configuration file in program folder is accepted and used and no configuration file is re-created in AppData.

Good work, thank you for implementing portable mode!

You don't keep change log. don't you?

**Comment by Martchus** [comment]
Thanks. Regarding logs, there's only the Git log (but no condensed version). However, the commit shouldn't have been hard to spot in the Git commit log.
