### ISSUE TITLE
The thumbnail does not appear.

### ISSUE THREAD

**Issue by FanserviceArchive** [Martchus/tageditor#91]
I was adding thumbnails to some H264 .mp4 videos, but some of them appear to be successful but the thumbnail is not added. The old thumbnail is also deleted. Only the VLC logo appears.

I couldn't find the difference between videos where the embedding was successful and not.

**Comment by Martchus** [comment]
With that much information I cannot help you. It is most likely a limitation of the files browser you're using. If you think it is a bug in the tag editor I need more details, e.g. some sample files.

**Comment by FanserviceArchive** [comment]
I am using Windows 11. Using mp3tag for files where the thumbnail doesn't work fixed the issue.

**Comment by Martchus** [comment]
Then it might actually be a bug. So I'd generally be interested in fixing it but I'd still need more information.

**Comment by FanserviceArchive** [comment]
I'm making videos for Patreon so I can't upload them here. If you write an e-mail, I can help.

**Comment by Martchus** [comment]
You can send me an e-mail. May address is present as meta-data on all my commits within this repository (e.g. see [the currently latest commit](https://github.com/Martchus/tageditor/commit/0198132739f6f4bc018cf9949829ee44b1211da8.patch)).

A version of the file before adding the cover and the cover you're trying to add would be good.

Note that normally one should also write "Steps to reproduce" when filing a bug report - even if it seems obvious. I assume you've just opened the file via the GUI and added the image supposed to be shown as thumbnail as cover. I also assume you've been using the most recent version of Tag Editor and the x86_64 Windows binary from the release section on GitHub. Is all of that correct? If you've used the CLI it would be good to know the CLI arguments you've been using.
