### ISSUE TITLE
[Feature] Search and replace tag information for tageditor-cli

### ISSUE THREAD

**Issue by GUUser91** [Martchus/tageditor#95]
Would it be possible if you can include a feature for tageditor-cli where it can search and replace tag information?
For example, let's say I have a song where the artist info is Koji Kondo, Yoshie Arakawa, Yoshinori Kawamoto and I want a command where it searches for the artist info Koji Kondo and replace it with 近藤浩治. I want the result to turn from this
`Koji Kondo, Yoshie Arakawa, Yoshinori Kawamoto`
to this
`近藤浩治, Yoshie Arakawa, Yoshinori Kawamoto`

**Comment by Martchus** [comment]
Is this about renaming files within the filesystem using tag information? That's already possible via the GUI.

Or is this is about searching by tag information now (and also replacing tag information)? That's not possible so far. Usually using `find` to search by the file or directory name was good enough for me (especially combined with the GUI's renaming feature). And setting just a single field to something should do the trick as well.

I'm not sure whether it makes sense to provide a specific syntax for all kinds of use cases. Maybe it would make more sense to expose the underlying library via Python or some other scripting language. (Of course you can already use the underlying library from C++ which has some convenient to use filesystem library theses days.)
